export type NewVersionCopy = {
  headline: [string, string];
  filters: [string, string, string];
  cards: [string, string][];
  imageAlt: (index: number) => string;
  stickerAlt: (index: number) => string;
};

const en: NewVersionCopy = {
  headline: ['A real Clipboard', 'in your Keyboard.'],
  filters: ['Text', 'Image', 'Sticker'],
  cards: [
    ['Product launch notes', 'A few thoughtful details can make the entire experience feel clearer, calmer, and easier to use from the very first tap.'],
    ['A tiny reminder', 'Take a short walk, refill your water, and return to the hard problem with a little more room to think.'],
    ['Meeting follow-up', 'Thanks for a thoughtful conversation. I’ve captured the key decisions and added the next steps we agreed on.'],
    ['Paste-ready copy', 'Save the useful things you write once, then paste them into a message whenever you need them.'],
    ['Weekend plans', 'Coffee at the little place on the corner, then a slow walk through the park if the weather holds.'],
    ['A good idea', 'Make the first version simple enough to share today, then let real feedback guide what comes next.'],
    ['Order reference', 'The package is expected Thursday afternoon. Leave it by the front desk if nobody is at the studio.'],
    ['Quick recipe', 'Toast the bread, add sliced avocado and lemon, then finish with flaky salt and a little chili oil.'],
    ['Design feedback', 'The spacing feels much calmer now. Let’s keep the buttons consistent and give the headline more room.'],
    ['Address', '18 Orchard Road, #04-12, Singapore 238823. The entrance is just beside the small bookshop.'],
    ['Reading list', 'Save the articles you want to revisit, along with a short note about why each one caught your attention.'],
    ['Voice memo note', 'Try the warmer version for the opening, keep the shorter ending, and send both options before lunch.'],
  ],
  imageAlt: (i) => `Clipboard image ${i}`,
  stickerAlt: (i) => `Happy sticker ${i}`,
};

// Localized copy for the complete set of languages offered by the language picker.
const localized: Record<string, Omit<NewVersionCopy, 'imageAlt' | 'stickerAlt'>> = {
  vi: { headline: ['Một Bảng Nhớ Tạm thực sự', 'trong Bàn Phím của bạn.'], filters: ['Văn bản', 'Hình ảnh', 'Nhãn dán'], cards: [
    ['Ghi chú ra mắt sản phẩm', 'Chỉ vài chi tiết tinh tế cũng giúp trải nghiệm rõ ràng, dễ chịu và dễ dùng hơn ngay từ lần chạm đầu tiên.'], ['Nhắc nhở nhỏ', 'Đi dạo một chút, uống thêm nước rồi quay lại với vấn đề khó cùng một tâm trí thoải mái hơn.'], ['Theo dõi cuộc họp', 'Cảm ơn bạn về cuộc trò chuyện hữu ích. Tôi đã ghi lại các quyết định chính và những bước tiếp theo chúng ta đã thống nhất.'], ['Nội dung sẵn sàng dán', 'Lưu lại những nội dung hữu ích bạn thường viết để dán vào tin nhắn bất cứ khi nào cần.'], ['Kế hoạch cuối tuần', 'Uống cà phê ở quán nhỏ góc phố, rồi thong thả đi dạo trong công viên nếu thời tiết đẹp.'], ['Một ý tưởng hay', 'Tạo phiên bản đầu tiên đủ đơn giản để chia sẻ hôm nay, rồi dùng phản hồi thực tế để định hướng bước tiếp theo.'], ['Thông tin đơn hàng', 'Gói hàng dự kiến đến vào chiều thứ Năm. Hãy để ở quầy lễ tân nếu không có ai tại studio.'], ['Công thức nhanh', 'Nướng bánh mì, thêm bơ quả và chanh thái lát, rồi rắc muối hạt cùng một chút dầu ớt.'], ['Góp ý thiết kế', 'Khoảng cách giờ trông thoáng hơn nhiều. Hãy giữ các nút nhất quán và chừa thêm không gian cho tiêu đề.'], ['Địa chỉ', '18 Orchard Road, #04-12, Singapore 238823. Lối vào nằm ngay cạnh hiệu sách nhỏ.'], ['Danh sách đọc', 'Lưu bài viết muốn đọc lại cùng một ghi chú ngắn về điều khiến bạn chú ý.'], ['Ghi chú thoại', 'Thử cách mở đầu ấm áp hơn, giữ phần kết ngắn gọn và gửi cả hai lựa chọn trước bữa trưa.'], ] },
  ja: { headline: ['本格的なクリップボードを', 'キーボードに。'], filters: ['テキスト', '画像', 'ステッカー'], cards: [
    ['製品リリースのメモ', '細やかな工夫を少し加えるだけで、最初のタップから体験がより明快で心地よく、使いやすくなります。'], ['小さなリマインダー', '少し散歩して水を補給したら、頭に余裕をもって難しい課題に戻りましょう。'], ['会議のフォローアップ', '有意義なお話をありがとうございました。主な決定事項と合意した次のステップを記録しました。'], ['すぐに貼り付けられる文章', 'よく使う文章を一度保存すれば、必要なときにいつでもメッセージへ貼り付けられます。'], ['週末の予定', '角の小さなお店でコーヒーを飲み、天気がよければ公園をゆっくり散歩。'], ['いいアイデア', '今日共有できるシンプルな初版を作り、実際の反応を次の改善に活かしましょう。'], ['注文情報', '荷物は木曜午後に届く予定です。スタジオに誰もいなければ受付に預けてください。'], ['簡単レシピ', 'パンを焼き、スライスしたアボカドとレモンをのせ、粗塩と少量のチリオイルで仕上げます。'], ['デザインのフィードバック', '余白がずっと落ち着いた印象になりました。ボタンの一貫性を保ち、見出しに余裕を持たせましょう。'], ['住所', 'シンガポール 238823、オーチャード・ロード18、#04-12。小さな書店のすぐ隣が入口です。'], ['読書リスト', '読み返したい記事を、気になった理由の短いメモと一緒に保存しましょう。'], ['音声メモ', '冒頭はより温かい案を試し、短い結びを使って、昼食前に両方の案を送りましょう。'], ] },
  es: { headline: ['Un portapapeles de verdad', 'en tu teclado.'], filters: ['Texto', 'Imagen', 'Sticker'], cards: [
    ['Notas del lanzamiento', 'Unos pocos detalles bien pensados hacen que la experiencia sea más clara, tranquila y fácil desde el primer toque.'], ['Un pequeño recordatorio', 'Da un paseo corto, bebe agua y vuelve al problema difícil con más espacio para pensar.'], ['Seguimiento de la reunión', 'Gracias por la conversación. He anotado las decisiones clave y los próximos pasos acordados.'], ['Texto listo para pegar', 'Guarda lo que escribes a menudo y pégalo en un mensaje cuando lo necesites.'], ['Planes para el fin de semana', 'Un café en el pequeño local de la esquina y un paseo tranquilo por el parque si acompaña el tiempo.'], ['Una buena idea', 'Haz una primera versión sencilla para compartir hoy y deja que los comentarios reales guíen lo siguiente.'], ['Referencia del pedido', 'El paquete llegará el jueves por la tarde. Déjalo en recepción si no hay nadie en el estudio.'], ['Receta rápida', 'Tuesta el pan, añade aguacate y limón en rodajas, y termina con sal en escamas y un poco de aceite picante.'], ['Comentarios de diseño', 'El espaciado se siente mucho más despejado. Mantengamos los botones coherentes y demos más aire al título.'], ['Dirección', '18 Orchard Road, #04-12, Singapur 238823. La entrada está junto a la pequeña librería.'], ['Lista de lectura', 'Guarda los artículos que quieras volver a leer con una nota breve sobre lo que te llamó la atención.'], ['Nota de voz', 'Prueba una apertura más cálida, conserva el cierre breve y envía ambas opciones antes de comer.'], ] },
  'zh-CN': { headline: ['真正好用的剪贴板', '就在你的键盘里。'], filters: ['文本', '图片', '贴纸'], cards: [
    ['产品发布笔记', '几个贴心细节，就能让体验从第一次点击起变得更清晰、更轻松，也更易上手。'], ['一个小提醒', '出去散会儿步，补充些水分，再带着更开阔的思路回来解决难题。'], ['会议后续', '感谢这次有益的交流。我已记录关键决定和我们商定的后续步骤。'], ['随时可粘贴的内容', '把常用内容保存一次，需要时就能粘贴到消息中。'], ['周末计划', '先去街角小店喝杯咖啡，天气允许的话再去公园慢慢散步。'], ['一个好点子', '先做出今天就能分享的简洁初版，再根据真实反馈决定下一步。'], ['订单信息', '包裹预计周四下午送达。如果工作室没人，请放在前台。'], ['简易食谱', '烤好面包，加入切片牛油果和柠檬，最后撒上海盐和少许辣椒油。'], ['设计反馈', '现在的间距舒服多了。保持按钮风格一致，并给标题留出更多空间。'], ['地址', '新加坡乌节路 18 号 #04-12，邮编 238823。入口就在小书店旁边。'], ['阅读清单', '保存想重读的文章，并附上一句吸引你注意的原因。'], ['语音备忘', '开头试试更温暖的版本，保留较短的结尾，并在午餐前发出两个选项。'], ] },
  'zh-TW': { headline: ['真正好用的剪貼簿', '就在你的鍵盤裡。'], filters: ['文字', '圖片', '貼圖'], cards: [
    ['產品發布筆記', '幾個貼心細節，就能讓體驗從第一次點擊起變得更清楚、更從容，也更容易上手。'], ['一個小提醒', '出去散散步、補充水分，再帶著更開闊的思緒回來處理難題。'], ['會議後續', '感謝這次有建設性的交流。我已記下重要決議和我們談好的後續步驟。'], ['隨時可貼上的內容', '把常用內容儲存一次，需要時就能貼到訊息裡。'], ['週末計畫', '先到街角小店喝杯咖啡，天氣許可的話再去公園慢慢散步。'], ['好點子', '先做出今天就能分享的簡單初版，再讓實際回饋引導下一步。'], ['訂單資訊', '包裹預計週四下午送達。若工作室沒人，請放在櫃檯。'], ['快速食譜', '烤好麵包，加入切片酪梨和檸檬，最後撒上片鹽和少許辣椒油。'], ['設計回饋', '現在的間距舒服多了。讓按鈕保持一致，並為標題多留一些空間。'], ['地址', '新加坡烏節路 18 號 #04-12，郵遞區號 238823。入口就在小書店旁。'], ['閱讀清單', '儲存想重讀的文章，並附上一句吸引你注意的原因。'], ['語音備忘', '開頭試試較溫暖的版本，保留精簡的結尾，午餐前送出兩種選項。'], ] },
};

// Other languages use carefully localized interface labels and headline; card examples fall back to English until their locale has a dedicated editorial set.
const headlines: Record<string, NewVersionCopy['headline']> = {
  fr: ['Un vrai presse-papiers', 'dans votre clavier.'], de: ['Eine echte Zwischenablage', 'auf deiner Tastatur.'], ru: ['Настоящий буфер обмена', 'прямо в клавиатуре.'], ko: ['진짜 클립보드를', '키보드 안에.'], hi: ['एक असली क्लिपबोर्ड', 'आपके कीबोर्ड में।'], bn: ['একটি আসল ক্লিপবোর্ড', 'আপনার কিবোর্ডে।'], id: ['Clipboard sungguhan', 'di Keyboard Anda.'], it: ['Una vera clipboard', 'nella tua tastiera.'], th: ['คลิปบอร์ดตัวจริง', 'บนคีย์บอร์ดของคุณ'], tl: ['Isang tunay na clipboard', 'nasa keyboard mo.'], pl: ['Prawdziwy schowek', 'w Twojej klawiaturze.'], tr: ['Gerçek bir pano', 'klavyenizde.'], 'pt-BR': ['Uma área de transferência de verdade', 'no seu teclado.'],
};
const filterLabels: Record<string, NewVersionCopy['filters']> = {
  fr: ['Texte', 'Image', 'Autocollant'], de: ['Text', 'Bild', 'Sticker'], ru: ['Текст', 'Изображение', 'Стикер'], ko: ['텍스트', '이미지', '스티커'], hi: ['टेक्स्ट', 'इमेज', 'स्टिकर'], bn: ['টেক্সট', 'ছবি', 'স্টিকার'], id: ['Teks', 'Gambar', 'Stiker'], it: ['Testo', 'Immagine', 'Adesivo'], th: ['ข้อความ', 'รูปภาพ', 'สติกเกอร์'], tl: ['Text', 'Larawan', 'Sticker'], pl: ['Tekst', 'Obraz', 'Naklejka'], tr: ['Metin', 'Görsel', 'Çıkartma'], 'pt-BR': ['Texto', 'Imagem', 'Figurinha'],
};

// Text cards need their own translations too; otherwise the marquee silently
// falls back to English for every locale without an editorial card set above.
const translatedCards: Record<string, NewVersionCopy['cards']> = {
  fr: [
    ['Notes de lancement', 'Quelques détails bien pensés rendent l’expérience plus claire, plus calme et plus simple dès le premier geste.'], ['Petit rappel', 'Faites une courte promenade, buvez un peu d’eau et reprenez ce problème avec les idées plus claires.'], ['Suivi de réunion', 'Merci pour cet échange. J’ai noté les décisions clés et les prochaines étapes convenues.'], ['Texte prêt à coller', 'Enregistrez les textes utiles que vous écrivez et collez-les dans un message quand vous en avez besoin.'], ['Projets du week-end', 'Un café dans le petit établissement du coin, puis une promenade au parc si le temps le permet.'], ['Une bonne idée', 'Créez aujourd’hui une première version simple à partager, puis laissez les retours guider la suite.'], ['Référence de commande', 'Le colis est attendu jeudi après-midi. Laissez-le à l’accueil si personne n’est au studio.'], ['Recette rapide', 'Faites griller le pain, ajoutez avocat et citron, puis terminez avec du sel et un filet d’huile pimentée.'], ['Retour sur le design', 'L’espacement paraît bien plus équilibré. Gardons des boutons cohérents et laissons respirer le titre.'], ['Adresse', '18 Orchard Road, #04-12, Singapour 238823. L’entrée se trouve juste à côté de la petite librairie.'], ['À lire', 'Enregistrez les articles à relire avec une courte note sur ce qui a retenu votre attention.'], ['Note vocale', 'Essayez une introduction plus chaleureuse, gardez la conclusion courte et envoyez les deux versions avant midi.'],
  ],
  de: [
    ['Notizen zum Start', 'Schon wenige durchdachte Details machen das Erlebnis vom ersten Tippen an klarer und angenehmer.'], ['Kleine Erinnerung', 'Geh kurz spazieren, trink etwas Wasser und kehr mit freiem Kopf zum schwierigen Problem zurück.'], ['Besprechungsnotiz', 'Danke für das gute Gespräch. Ich habe die wichtigsten Entscheidungen und nächsten Schritte festgehalten.'], ['Text zum Einfügen', 'Speichere hilfreiche Texte einmal und füge sie bei Bedarf direkt in eine Nachricht ein.'], ['Wochenendpläne', 'Kaffee im kleinen Laden an der Ecke und danach ein Spaziergang im Park, wenn das Wetter mitspielt.'], ['Gute Idee', 'Teile heute eine einfache erste Version und lass echtes Feedback die nächsten Schritte bestimmen.'], ['Bestellnummer', 'Das Paket kommt voraussichtlich Donnerstag Nachmittag. Bitte an der Rezeption abgeben, falls niemand im Studio ist.'], ['Schnelles Rezept', 'Brot toasten, Avocado und Zitrone daraufgeben und mit Salz und etwas Chiliöl abrunden.'], ['Design-Feedback', 'Der Abstand wirkt jetzt viel ruhiger. Halten wir die Buttons einheitlich und geben der Überschrift mehr Raum.'], ['Adresse', '18 Orchard Road, #04-12, Singapur 238823. Der Eingang liegt direkt neben dem kleinen Buchladen.'], ['Leseliste', 'Speichere Artikel zum späteren Lesen mit einer kurzen Notiz dazu, was dich daran interessiert.'], ['Sprachnotiz', 'Probiere einen wärmeren Einstieg, behalte den kurzen Schluss und sende beide Varianten vor dem Mittagessen.'],
  ],
  ru: [
    ['Заметки к запуску', 'Несколько продуманных деталей сделают работу понятнее и приятнее уже с первого касания.'], ['Небольшое напоминание', 'Немного прогуляйтесь, выпейте воды и вернитесь к сложной задаче со свежими мыслями.'], ['Итоги встречи', 'Спасибо за содержательный разговор. Я записал основные решения и согласованные следующие шаги.'], ['Текст для вставки', 'Сохраняйте полезные тексты и вставляйте их в сообщение, когда понадобится.'], ['Планы на выходные', 'Кофе в маленьком кафе за углом, а затем прогулка по парку, если погода позволит.'], ['Хорошая идея', 'Поделитесь сегодня простой первой версией и опирайтесь на реальные отзывы.'], ['Номер заказа', 'Посылка ожидается в четверг днём. Если в студии никого нет, оставьте её у стойки.'], ['Быстрый рецепт', 'Поджарьте хлеб, добавьте авокадо и лимон, затем посыпьте солью и сбрызните острым маслом.'], ['Отзыв о дизайне', 'Теперь отступы выглядят спокойнее. Сохраним единый стиль кнопок и добавим заголовку воздуха.'], ['Адрес', '18 Orchard Road, #04-12, Сингапур 238823. Вход находится рядом с небольшим книжным магазином.'], ['Список чтения', 'Сохраняйте статьи, к которым хотите вернуться, и добавляйте короткую заметку о них.'], ['Голосовая заметка', 'Попробуйте более тёплое начало, оставьте короткий финал и отправьте оба варианта до обеда.'],
  ],
  ko: [
    ['출시 메모', '작은 배려 몇 가지가 첫 터치부터 더 명확하고 편안한 경험을 만들어 줍니다.'], ['작은 알림', '잠깐 산책하고 물을 마신 뒤, 한결 가벼운 마음으로 어려운 문제를 다시 살펴보세요.'], ['회의 후속 메모', '좋은 대화 감사합니다. 주요 결정 사항과 합의한 다음 단계를 정리해 두었습니다.'], ['붙여넣기용 문구', '자주 쓰는 문구를 저장해 두고 필요할 때 메시지에 바로 붙여넣으세요.'], ['주말 계획', '모퉁이의 작은 카페에서 커피를 마시고 날씨가 좋으면 공원을 천천히 산책해요.'], ['좋은 아이디어', '오늘 공유할 수 있는 간단한 첫 버전을 만들고 실제 의견을 바탕으로 다음 단계를 정하세요.'], ['주문 정보', '택배는 목요일 오후 도착 예정입니다. 스튜디오에 사람이 없으면 프런트에 맡겨 주세요.'], ['간단한 레시피', '빵을 굽고 아보카도와 레몬을 올린 뒤 굵은 소금과 칠리 오일을 더하세요.'], ['디자인 의견', '간격이 훨씬 편안해졌어요. 버튼은 일관되게 유지하고 제목에 여유를 주세요.'], ['주소', '싱가포르 238823, 오차드 로드 18, #04-12. 작은 서점 바로 옆에 입구가 있습니다.'], ['읽을거리', '다시 읽고 싶은 글과 눈길을 끈 이유를 짧은 메모로 함께 저장하세요.'], ['음성 메모', '더 따뜻한 시작을 시도하고 짧은 마무리는 유지한 뒤 점심 전에 두 안을 보내세요.'],
  ],
  hi: [
    ['प्रोडक्ट लॉन्च नोट्स', 'कुछ सोच-समझकर जोड़ी गई बातें पहले टैप से अनुभव को अधिक स्पष्ट और आसान बनाती हैं।'], ['एक छोटा रिमाइंडर', 'थोड़ी देर टहलें, पानी पिएँ और नए विचारों के साथ मुश्किल काम पर लौटें।'], ['मीटिंग के बाद', 'अच्छी बातचीत के लिए धन्यवाद। मैंने मुख्य निर्णय और तय किए गए अगले कदम लिख लिए हैं।'], ['पेस्ट करने के लिए तैयार', 'काम के टेक्स्ट को एक बार सेव करें और ज़रूरत पड़ने पर संदेश में पेस्ट करें।'], ['वीकेंड की योजना', 'कोने वाले छोटे कैफ़े में कॉफ़ी, फिर मौसम ठीक हो तो पार्क में आराम से सैर।'], ['एक अच्छा विचार', 'आज साझा करने लायक सरल पहला रूप बनाएँ और आगे के लिए असली सुझावों से सीखें।'], ['ऑर्डर जानकारी', 'पार्सल गुरुवार दोपहर तक आने की उम्मीद है। स्टूडियो में कोई न हो तो रिसेप्शन पर छोड़ दें।'], ['झटपट रेसिपी', 'ब्रेड टोस्ट करें, एवोकाडो और नींबू डालें, फिर नमक और थोड़ा तीखा तेल छिड़कें।'], ['डिज़ाइन सुझाव', 'अब स्पेसिंग कहीं अधिक सहज लगती है। बटन एक जैसे रखें और शीर्षक को थोड़ी जगह दें।'], ['पता', '18 Orchard Road, #04-12, Singapore 238823. प्रवेश छोटे किताबघर के ठीक पास है।'], ['पढ़ने की सूची', 'बाद में पढ़ने वाले लेखों को इस छोटी टिप्पणी के साथ सेव करें कि वे क्यों पसंद आए।'], ['वॉइस मेमो', 'शुरुआत को थोड़ा गर्मजोशी भरा करें, छोटा अंत रखें और दोपहर के भोजन से पहले दोनों विकल्प भेजें।'],
  ],
  bn: [
    ['পণ্য উন্মোচনের নোট', 'কিছু চিন্তাশীল খুঁটিনাটি প্রথম স্পর্শ থেকেই অভিজ্ঞতাকে আরও পরিষ্কার ও সহজ করে তোলে।'], ['ছোট্ট মনে করিয়ে দেওয়া', 'একটু হাঁটুন, পানি পান করুন, তারপর নতুন মনোযোগ নিয়ে কঠিন কাজে ফিরুন।'], ['মিটিংয়ের পরের নোট', 'ভালো আলোচনার জন্য ধন্যবাদ। মূল সিদ্ধান্ত ও সম্মত পরবর্তী পদক্ষেপগুলো লিখে রেখেছি।'], ['পেস্ট করার জন্য প্রস্তুত', 'দরকারি লেখা একবার সংরক্ষণ করুন, প্রয়োজন হলে বার্তায় পেস্ট করুন।'], ['সপ্তাহান্তের পরিকল্পনা', 'মোড়ের ছোট দোকানে কফি, তারপর আবহাওয়া ভালো থাকলে পার্কে ধীর পায়ে হাঁটা।'], ['একটি ভালো ভাবনা', 'আজই ভাগ করে নেওয়ার মতো সহজ প্রথম সংস্করণ বানান, তারপর বাস্তব মতামত থেকে পরের ধাপ ঠিক করুন।'], ['অর্ডারের তথ্য', 'পার্সেলটি বৃহস্পতিবার বিকেলে আসার কথা। স্টুডিওতে কেউ না থাকলে সামনের ডেস্কে রাখুন।'], ['সহজ রেসিপি', 'রুটি টোস্ট করে অ্যাভোকাডো ও লেবু দিন, শেষে মোটা লবণ ও সামান্য ঝাল তেল ছড়ান।'], ['ডিজাইন মতামত', 'এখন ফাঁকগুলো অনেক স্বস্তিদায়ক লাগছে। বোতাম একরকম রাখি, শিরোনামকে আরও জায়গা দিই।'], ['ঠিকানা', '18 Orchard Road, #04-12, Singapore 238823. ছোট বইয়ের দোকানের পাশেই প্রবেশপথ।'], ['পড়ার তালিকা', 'আবার পড়তে চান এমন নিবন্ধ সংরক্ষণ করুন, সঙ্গে কেন ভালো লেগেছে তার ছোট্ট নোট রাখুন।'], ['ভয়েস নোট', 'শুরুর অংশটি আরও উষ্ণ করে দেখুন, ছোট সমাপ্তিটি রাখুন এবং দুপুরের আগে দুটি বিকল্প পাঠান।'],
  ],
  id: [
    ['Catatan peluncuran', 'Beberapa detail yang dipikirkan dengan baik membuat pengalaman terasa lebih jelas dan mudah sejak awal.'], ['Pengingat kecil', 'Jalan sebentar, minum air, lalu kembali ke masalah sulit dengan pikiran lebih segar.'], ['Tindak lanjut rapat', 'Terima kasih atas percakapannya. Keputusan utama dan langkah berikutnya sudah saya catat.'], ['Teks siap ditempel', 'Simpan teks yang sering digunakan, lalu tempelkan ke pesan saat dibutuhkan.'], ['Rencana akhir pekan', 'Ngopi di kedai kecil di sudut, lalu berjalan santai di taman jika cuaca mendukung.'], ['Ide bagus', 'Bagikan versi awal yang sederhana hari ini, lalu biarkan masukan nyata menentukan langkah berikutnya.'], ['Referensi pesanan', 'Paket diperkirakan tiba Kamis sore. Titipkan di meja depan jika tidak ada orang di studio.'], ['Resep cepat', 'Panggang roti, tambahkan alpukat dan lemon, lalu beri garam kasar dan sedikit minyak cabai.'], ['Masukan desain', 'Jaraknya kini terasa lebih lega. Samakan gaya tombol dan beri judul lebih banyak ruang.'], ['Alamat', '18 Orchard Road, #04-12, Singapura 238823. Pintu masuk tepat di sebelah toko buku kecil.'], ['Daftar bacaan', 'Simpan artikel yang ingin dibaca lagi beserta catatan singkat tentang hal yang menarik perhatian.'], ['Catatan suara', 'Coba pembuka yang lebih hangat, pertahankan penutup singkat, dan kirim kedua opsi sebelum makan siang.'],
  ],
  it: [
    ['Note sul lancio', 'Pochi dettagli curati rendono l’esperienza più chiara e semplice fin dal primo tocco.'], ['Un piccolo promemoria', 'Fai una breve passeggiata, bevi un po’ d’acqua e torna al problema con la mente più libera.'], ['Seguito della riunione', 'Grazie per la conversazione. Ho annotato le decisioni principali e i prossimi passi concordati.'], ['Testo pronto da incollare', 'Salva i testi utili che scrivi e incollali in un messaggio quando ti servono.'], ['Piani per il weekend', 'Un caffè nel piccolo locale all’angolo e poi una passeggiata al parco, se il tempo regge.'], ['Una buona idea', 'Condividi oggi una prima versione semplice e lascia che siano i riscontri reali a guidare il seguito.'], ['Riferimento ordine', 'Il pacco è previsto per giovedì pomeriggio. Lascialo alla reception se non c’è nessuno in studio.'], ['Ricetta veloce', 'Tosta il pane, aggiungi avocado e limone, poi completa con sale in fiocchi e un filo d’olio piccante.'], ['Feedback sul design', 'Gli spazi ora sono più equilibrati. Manteniamo coerenti i pulsanti e diamo più respiro al titolo.'], ['Indirizzo', '18 Orchard Road, #04-12, Singapore 238823. L’ingresso è accanto alla piccola libreria.'], ['Letture da fare', 'Salva gli articoli da rileggere con una breve nota su ciò che ha attirato la tua attenzione.'], ['Nota vocale', 'Prova un’apertura più calda, mantieni il finale breve e invia entrambe le opzioni prima di pranzo.'],
  ],
  th: [
    ['บันทึกเปิดตัวสินค้า', 'รายละเอียดเล็ก ๆ ที่ใส่ใจช่วยให้ประสบการณ์ชัดเจนและใช้งานง่ายขึ้นตั้งแต่ครั้งแรก'], ['เตือนความจำเล็ก ๆ', 'ออกไปเดินสักครู่ ดื่มน้ำ แล้วกลับมาคิดเรื่องยากด้วยสมองที่ปลอดโปร่งขึ้น'], ['ติดตามการประชุม', 'ขอบคุณสำหรับการพูดคุย ฉันจดประเด็นสำคัญและขั้นตอนถัดไปที่ตกลงกันไว้แล้ว'], ['ข้อความพร้อมวาง', 'บันทึกข้อความที่ใช้บ่อยไว้ แล้ววางลงในแชตได้ทุกเมื่อที่ต้องการ'], ['แผนสุดสัปดาห์', 'แวะดื่มกาแฟที่ร้านเล็กตรงหัวมุม แล้วเดินเล่นในสวนถ้าอากาศเป็นใจ'], ['ไอเดียดี ๆ', 'ทำฉบับแรกที่เรียบง่ายเพื่อแชร์วันนี้ แล้วใช้ความคิดเห็นจริงกำหนดขั้นต่อไป'], ['ข้อมูลคำสั่งซื้อ', 'พัสดุน่าจะมาถึงบ่ายวันพฤหัสบดี หากไม่มีใครอยู่ที่สตูดิโอ ฝากไว้ที่แผนกต้อนรับ'], ['สูตรง่าย ๆ', 'ปิ้งขนมปัง ใส่อะโวคาโดกับเลมอน แล้วโรยเกลือและน้ำมันพริกเล็กน้อย'], ['ข้อเสนอแนะด้านดีไซน์', 'ระยะห่างดูสบายตาขึ้นมาก รักษารูปแบบปุ่มให้สม่ำเสมอและเพิ่มพื้นที่ให้หัวข้อ'], ['ที่อยู่', '18 Orchard Road, #04-12, Singapore 238823 ทางเข้าอยู่ข้างร้านหนังสือเล็ก ๆ'], ['รายการอ่าน', 'บันทึกบทความที่อยากกลับมาอ่าน พร้อมโน้ตสั้น ๆ ว่าอะไรทำให้สนใจ'], ['บันทึกเสียง', 'ลองใช้ประโยคเปิดที่อบอุ่นขึ้น คงตอนจบที่สั้นไว้ แล้วส่งทั้งสองแบบก่อนมื้อกลางวัน'],
  ],
  tl: [
    ['Mga tala sa paglulunsad', 'Mas nagiging malinaw at madaling gamitin ang karanasan dahil sa ilang detalyeng pinag-isipan.'], ['Munting paalala', 'Maglakad sandali, uminom ng tubig, at balikan ang mahirap na gawain nang mas presko ang isip.'], ['Kasunod ng pulong', 'Salamat sa makabuluhang usapan. Itinala ko ang mahahalagang pasya at mga susunod na hakbang.'], ['Handang i-paste na teksto', 'I-save ang mga kapaki-pakinabang na tekstong isinusulat mo at i-paste sa mensahe kapag kailangan.'], ['Mga plano sa weekend', 'Kape sa maliit na tindahan sa kanto, saka dahan-dahang mamasyal sa parke kung maganda ang panahon.'], ['Magandang ideya', 'Gumawa ng simpleng unang bersyon na maibabahagi ngayon, at hayaang gabayan ng tunay na puna ang susunod.'], ['Impormasyon ng order', 'Inaasahang darating ang pakete sa Huwebes ng hapon. Iwan sa front desk kung walang tao sa studio.'], ['Mabilis na recipe', 'I-toast ang tinapay, lagyan ng abokado at lemon, saka budburan ng asin at kaunting sili na mantika.'], ['Puna sa disenyo', 'Mas maaliwalas na ang pagitan. Panatilihing pare-pareho ang mga button at bigyan ng espasyo ang pamagat.'], ['Address', '18 Orchard Road, #04-12, Singapore 238823. Katabi mismo ng maliit na tindahan ng libro ang pasukan.'], ['Listahan ng babasahin', 'I-save ang mga artikulong babalikan at magdagdag ng maikling tala kung bakit ka naakit dito.'], ['Tala ng boses', 'Subukan ang mas mainit na pambungad, panatilihin ang maikling pagtatapos, at ipadala ang dalawang opsyon bago magtanghalian.'],
  ],
  pl: [
    ['Notatki o premierze', 'Kilka przemyślanych szczegółów sprawia, że korzystanie jest prostsze i przyjemniejsze od pierwszego dotknięcia.'], ['Małe przypomnienie', 'Wybierz się na krótki spacer, napij się wody i wróć do trudnego zadania ze świeżą głową.'], ['Podsumowanie spotkania', 'Dziękuję za rozmowę. Zapisałem najważniejsze decyzje i ustalone kolejne kroki.'], ['Tekst gotowy do wklejenia', 'Zapisuj przydatne teksty i wklejaj je do wiadomości, gdy będą potrzebne.'], ['Plany na weekend', 'Kawa w małym lokalu za rogiem, a potem spokojny spacer po parku, jeśli pogoda dopisze.'], ['Dobry pomysł', 'Udostępnij dziś prostą pierwszą wersję i pozwól, by prawdziwe opinie wskazały dalszy kierunek.'], ['Informacje o zamówieniu', 'Przesyłka powinna dotrzeć w czwartek po południu. Jeśli nikogo nie ma w studiu, zostaw ją w recepcji.'], ['Szybki przepis', 'Podpiecz chleb, dodaj awokado i cytrynę, a na koniec posyp solą i skrop ostrym olejem.'], ['Opinie o projekcie', 'Odstępy wyglądają teraz znacznie spokojniej. Ujednolićmy przyciski i dajmy nagłówkowi więcej miejsca.'], ['Adres', '18 Orchard Road, #04-12, Singapur 238823. Wejście znajduje się tuż obok małej księgarni.'], ['Lista lektur', 'Zapisuj artykuły do ponownego przeczytania wraz z krótką notatką, co Cię w nich zaciekawiło.'], ['Notatka głosowa', 'Wypróbuj cieplejszy początek, zachowaj krótkie zakończenie i wyślij obie wersje przed lunchem.'],
  ],
  tr: [
    ['Ürün lansmanı notları', 'Düşünülmüş birkaç küçük ayrıntı, deneyimi ilk dokunuştan itibaren daha anlaşılır ve kolay hale getirir.'], ['Küçük bir hatırlatma', 'Kısa bir yürüyüş yap, su iç ve zor probleme daha açık bir zihinle geri dön.'], ['Toplantı sonrası', 'Güzel sohbet için teşekkürler. Önemli kararları ve üzerinde anlaştığımız sonraki adımları not aldım.'], ['Yapıştırmaya hazır metin', 'Yararlı metinleri bir kez kaydet, gerektiğinde mesaja hemen yapıştır.'], ['Hafta sonu planı', 'Köşedeki küçük dükkânda kahve, hava güzelse ardından parkta sakin bir yürüyüş.'], ['Güzel bir fikir', 'Bugün paylaşılabilecek basit bir ilk sürüm hazırla, sonrasını gerçek geri bildirimler belirlesin.'], ['Sipariş bilgisi', 'Paketin perşembe öğleden sonra gelmesi bekleniyor. Stüdyoda kimse yoksa resepsiyona bırak.'], ['Kolay tarif', 'Ekmeği kızart, avokado ve limon ekle; üzerine iri tuz ve biraz acı yağ gezdir.'], ['Tasarım yorumu', 'Boşluklar artık çok daha ferah. Düğmeleri tutarlı tutalım ve başlığa daha fazla alan bırakalım.'], ['Adres', '18 Orchard Road, #04-12, Singapur 238823. Giriş küçük kitapçının hemen yanında.'], ['Okuma listesi', 'Yeniden okuyacağın yazıları, ilgini çeken noktaya dair kısa bir notla kaydet.'], ['Sesli not', 'Daha sıcak bir açılış dene, kısa bitişi koru ve öğle yemeğinden önce iki seçeneği de gönder.'],
  ],
  'pt-BR': [
    ['Notas de lançamento', 'Alguns detalhes bem pensados deixam a experiência mais clara e simples desde o primeiro toque.'], ['Lembrete rápido', 'Faça uma caminhada curta, beba água e volte ao problema difícil com a cabeça mais leve.'], ['Acompanhamento da reunião', 'Obrigado pela conversa. Anotei as principais decisões e os próximos passos combinados.'], ['Texto pronto para colar', 'Salve os textos úteis que você escreve e cole em uma mensagem quando precisar.'], ['Planos para o fim de semana', 'Um café no cantinho da esquina e depois uma caminhada tranquila no parque, se o tempo ajudar.'], ['Uma boa ideia', 'Crie uma primeira versão simples para compartilhar hoje e deixe o feedback real guiar o próximo passo.'], ['Referência do pedido', 'A encomenda deve chegar na quinta à tarde. Deixe na recepção se não houver ninguém no estúdio.'], ['Receita rápida', 'Toste o pão, acrescente abacate e limão e finalize com sal em flocos e um pouco de azeite apimentado.'], ['Feedback de design', 'O espaçamento ficou bem mais leve. Vamos manter os botões consistentes e dar mais espaço ao título.'], ['Endereço', '18 Orchard Road, #04-12, Singapura 238823. A entrada fica ao lado da pequena livraria.'], ['Lista de leitura', 'Salve os artigos que quer reler com uma nota curta sobre o que chamou sua atenção.'], ['Nota de voz', 'Experimente uma abertura mais acolhedora, mantenha o final curto e envie as duas opções antes do almoço.'],
  ],
};

const iosRequirement: Record<string, string> = {
  en: 'Requires iOS 26 or later',
  vi: 'Yêu cầu phiên bản iOS 26 trở lên',
  ja: 'iOS 26以降が必要です',
  es: 'Requiere iOS 26 o posterior',
  'zh-TW': '需要 iOS 26 或以上版本',
  'zh-CN': '需要 iOS 26 或更高版本',
  'pt-BR': 'Requer iOS 26 ou posterior',
  fr: 'Nécessite iOS 26 ou une version ultérieure',
  de: 'Erfordert iOS 26 oder neuer',
  ru: 'Требуется iOS 26 или новее',
  ko: 'iOS 26 이상이 필요합니다',
  hi: 'iOS 26 या उसके बाद का संस्करण आवश्यक है',
  bn: 'iOS 26 বা তার পরবর্তী সংস্করণ প্রয়োজন',
  id: 'Memerlukan iOS 26 atau versi lebih baru',
  it: 'Richiede iOS 26 o versione successiva',
  th: 'ต้องใช้ iOS 26 ขึ้นไป',
  tl: 'Nangangailangan ng iOS 26 o mas bago',
  pl: 'Wymaga systemu iOS 26 lub nowszego',
  tr: 'iOS 26 veya daha yenisi gerekir',
};

export const getNewVersionCopy = (lang: string): NewVersionCopy => {
  const selected = localized[lang];
  const base = selected ? { ...en, ...selected } : {
    ...en,
    cards: translatedCards[lang] ?? en.cards,
    headline: headlines[lang] ?? en.headline,
    filters: filterLabels[lang] ?? en.filters,
  };
  return {
    ...base,
    imageAlt: (index) => `${base.filters[1]} ${index}`,
    stickerAlt: (index) => `${base.filters[2]} ${index}`,
  };
};

export const getIosRequirement = (lang: string) => iosRequirement[lang] ?? iosRequirement.en;
