type FeatureDetails = {
  featureParagraphs: string[];
  actionTitles: string[];
  actionParagraphs: string[];
};

const en: FeatureDetails = {
  featureParagraphs: [
    'Create and edit multiple content templates so they are ready to send from your keyboard. Add email templates, greetings, contact information, website links, sample content, color codes, AI prompts, and draft posts.',
    'Store your favorite photos, memes, payment QR codes, and design mockups.',
    'Create stickers from your photo album or existing camera photos, turning your favorite stickers into something exclusively yours.',
  ],
  actionTitles: ['Groups', 'Pin', 'Copy', 'Duplicate', 'Export files', 'Import files', 'Filter', 'Search', 'Sort', 'System Pasteboard', 'Expiring content', 'iCloud sync'],
  actionParagraphs: [
    'Create groups and organize texts, images, and stickers by how you use them. Switch smoothly between groups in the keyboard app.',
    'Pin important texts, images, and stickers that you use often, so they are ready to send faster.',
    'Copy texts, images, and stickers to send or reuse them quickly.',
    'Duplicate texts, images, and stickers to create an editable version while preserving the original.',
    'Export your text data as JSON or CSV files through the Files app.',
    'Import JSON or CSV text data from the Files app to quickly restore or move your content.',
    'Filter content by type, group, or status to focus on what you need.',
    'Search saved texts, images, and stickers to find content instantly.',
    'Sort content your way so the most relevant items are always easy to reach.',
    'Use the System Pasteboard to bring copied content into LiquidBoard whenever you need it.',
    'Set content to expire automatically to keep temporary information private and uncluttered.',
    'Sync your content securely with iCloud so it stays available across your Apple devices.',
  ],
};

const vi: FeatureDetails = {
  featureParagraphs: [
    'Tạo và chỉnh sửa nhiều nội dung mẫu để sẵn sàng gửi đi từ bàn phím. Với văn bản bạn có thể thêm vào: email mẫu, lời chào, thông tin liên hệ, liên kết trang web, nội dung mẫu, mã màu, AI prompt, bài viết nháp.',
    'Lưu trữ ảnh yêu thích, meme, mã QR thanh toán, bản mockup thiết kế.',
    'Tạo nhãn dán từ album ảnh hoặc tạo từ ảnh chụp camera có sẵn để biến những nhãn dán yêu thích thành độc quyền của bạn.',
  ],
  actionTitles: ['Nhóm', 'Ghim', 'Sao chép', 'Nhân bản', 'Xuất file', 'Nhập file', 'Bộ lọc', 'Tìm kiếm', 'Sắp xếp', 'Bảng Tạm Hệ Thống', 'Nội dung tự huỷ', 'Đồng bộ iCloud'],
  actionParagraphs: [
    'Tạo nhóm và phân loại văn bản, ảnh, nhãn dán theo nhu cầu sử dụng. Chuyển đổi mượt mà giữa các nhóm trong ứng dụng bàn phím.',
    'Ghim văn bản, ảnh và nhãn dán quan trọng, thường dùng lên đầu để gửi nhanh hơn.',
    'Sao chép văn bản, ảnh và nhãn dán để gửi hoặc sử dụng lại nhanh chóng.',
    'Nhân bản văn bản, ảnh và nhãn dán để tạo bản có thể chỉnh sửa mà vẫn giữ nguyên nội dung gốc.',
    'Xuất dữ liệu văn bản thành tệp JSON hoặc CSV thông qua ứng dụng Files.',
    'Nhập dữ liệu văn bản JSON hoặc CSV từ ứng dụng Files để nhanh chóng khôi phục hoặc chuyển nội dung.',
    'Lọc nội dung theo loại, nhóm hoặc trạng thái để tập trung vào điều bạn cần.',
    'Tìm kiếm trong văn bản, ảnh và nhãn dán đã lưu để tìm nội dung ngay lập tức.',
    'Sắp xếp nội dung theo cách bạn muốn để các mục phù hợp luôn dễ truy cập.',
    'Dùng Bảng Tạm Hệ Thống để đưa nội dung đã sao chép vào LiquidBoard bất cứ khi nào cần.',
    'Thiết lập nội dung tự huỷ để giữ thông tin tạm thời riêng tư và gọn gàng.',
    'Đồng bộ nội dung an toàn với iCloud để luôn có sẵn trên các thiết bị Apple của bạn.',
  ],
};

const localized: Record<string, FeatureDetails> = {
  en,
  vi,
  ja: {
    featureParagraphs: ['キーボードからすぐ送れるよう、複数の定型コンテンツを作成・編集できます。メールテンプレート、あいさつ、連絡先、Webリンク、サンプル文、カラーコード、AIプロンプト、下書きを追加できます。', 'お気に入りの写真、ミーム、支払い用QRコード、デザインモックアップを保存できます。', '写真アルバムや既存のカメラ写真からステッカーを作成し、お気に入りを自分だけのステッカーにできます。'],
    actionTitles: ['グループ', 'ピン留め', 'コピー', '複製', 'ファイルを書き出す', 'ファイルを読み込む', 'フィルター', '検索', '並べ替え', 'システムクリップボード', '自動消去コンテンツ', 'iCloud同期'],
    actionParagraphs: ['グループを作成し、テキスト、画像、ステッカーを用途に応じて整理します。キーボードアプリ内でグループをスムーズに切り替えられます。', 'よく使う重要なテキスト、画像、ステッカーを上部にピン留めして、よりすばやく送信できます。', 'テキスト、画像、ステッカーをコピーして、すばやく送信または再利用できます。', '元の内容を残したまま、編集用にテキスト、画像、ステッカーを複製できます。', 'ファイルアプリを通じてテキストデータをJSONまたはCSVファイルとして書き出します。', 'ファイルアプリからJSONまたはCSVのテキストデータを読み込み、コンテンツをすばやく復元または移動します。', '種類、グループ、状態でコンテンツを絞り込み、必要なものに集中できます。', '保存したテキスト、画像、ステッカーを検索して、すぐに見つけられます。', '好みに合わせて並べ替え、関連する項目にいつでも簡単にアクセスできます。', 'システムクリップボードを使い、コピーしたコンテンツを必要なときにLiquidBoardへ取り込みます。', 'コンテンツを自動的に消去するよう設定し、一時的な情報を非公開かつ整理された状態に保ちます。', 'iCloudで安全に同期し、すべてのAppleデバイスでコンテンツを利用できます。'],
  },
  es: {
    featureParagraphs: ['Cree y edite varias plantillas de contenido para enviarlas desde el teclado. Añada plantillas de email, saludos, datos de contacto, enlaces web, contenido de muestra, códigos de color, prompts de IA y borradores.', 'Guarde sus fotos favoritas, memes, códigos QR de pago y maquetas de diseño.', 'Cree stickers desde su álbum de fotos o fotos existentes de la cámara para convertir sus favoritos en stickers exclusivos.'],
    actionTitles: ['Grupos', 'Fijar', 'Copiar', 'Duplicar', 'Exportar archivos', 'Importar archivos', 'Filtrar', 'Buscar', 'Ordenar', 'Portapapeles del sistema', 'Contenido con caducidad', 'Sincronización con iCloud'],
    actionParagraphs: ['Cree grupos y organice textos, imágenes y stickers según su uso. Cambie fluidamente entre grupos en la app de teclado.', 'Fije arriba los textos, imágenes y stickers importantes que usa con frecuencia para enviarlos más rápido.', 'Copie textos, imágenes y stickers para enviarlos o reutilizarlos rápidamente.', 'Duplique textos, imágenes y stickers para crear una versión editable sin perder el original.', 'Exporte sus datos de texto como archivos JSON o CSV desde la app Archivos.', 'Importe datos de texto JSON o CSV desde la app Archivos para restaurar o mover contenido rápidamente.', 'Filtre el contenido por tipo, grupo o estado para centrarse en lo que necesita.', 'Busque textos, imágenes y stickers guardados para encontrar contenido al instante.', 'Ordene el contenido a su manera para que los elementos relevantes sean fáciles de alcanzar.', 'Use el Portapapeles del sistema para llevar contenido copiado a LiquidBoard cuando lo necesite.', 'Configure contenido para que caduque automáticamente y mantenga la información temporal privada y ordenada.', 'Sincronice su contenido de forma segura con iCloud para tenerlo disponible en sus dispositivos Apple.'],
  },
  'zh-TW': {
    featureParagraphs: ['建立並編輯多個內容範本，隨時可從鍵盤傳送。可加入 Email 範本、問候語、聯絡資訊、網站連結、範例內容、色碼、AI 提示詞與文章草稿。', '儲存喜愛的照片、迷因、付款 QR Code 與設計 mockup。', '從相簿或現有相機照片建立貼圖，將喜愛的貼圖變成專屬於你的收藏。'],
    actionTitles: ['群組', '置頂', '複製', '建立副本', '匯出檔案', '匯入檔案', '篩選', '搜尋', '排序', '系統剪貼板', '自動刪除內容', 'iCloud 同步'],
    actionParagraphs: ['建立群組，依使用需求整理文字、圖片與貼圖。可在鍵盤 App 中流暢切換群組。', '將常用的重要文字、圖片與貼圖置頂，以便更快傳送。', '複製文字、圖片與貼圖，以便快速傳送或重複使用。', '建立文字、圖片與貼圖的可編輯副本，同時保留原始內容。', '透過檔案 App 將文字資料匯出為 JSON 或 CSV 檔案。', '從檔案 App 匯入 JSON 或 CSV 文字資料，快速還原或移動內容。', '依類型、群組或狀態篩選內容，專注於所需項目。', '搜尋已儲存的文字、圖片與貼圖，立即找到內容。', '依喜好排序內容，讓相關項目隨時容易存取。', '需要時使用系統剪貼板，將已複製的內容帶入 LiquidBoard。', '設定內容自動刪除，讓暫時資訊保持隱私與整潔。', '透過 iCloud 安全同步內容，讓所有 Apple 裝置都可使用。'],
  },
  'pt-BR': {
    featureParagraphs: ['Crie e edite vários modelos de conteúdo para enviar pelo teclado. Adicione modelos de email, saudações, contatos, links de sites, conteúdo de exemplo, códigos de cor, prompts de IA e rascunhos.', 'Guarde fotos favoritas, memes, códigos QR de pagamento e mockups de design.', 'Crie adesivos do álbum de fotos ou de fotos existentes da câmera e transforme seus favoritos em adesivos exclusivos.'],
    actionTitles: ['Grupos', 'Fixar', 'Copiar', 'Duplicar', 'Exportar arquivos', 'Importar arquivos', 'Filtrar', 'Pesquisar', 'Ordenar', 'Área de transferência do sistema', 'Conteúdo temporário', 'Sincronização com iCloud'],
    actionParagraphs: ['Crie grupos e organize textos, imagens e adesivos conforme o uso. Alterne entre grupos sem interrupção no teclado.', 'Fixe no topo textos, imagens e adesivos importantes que você usa com frequência para enviá-los mais rápido.', 'Copie textos, imagens e adesivos para enviar ou reutilizar rapidamente.', 'Duplique textos, imagens e adesivos para criar uma versão editável e preservar o original.', 'Exporte dados de texto como arquivos JSON ou CSV pelo app Arquivos.', 'Importe dados de texto JSON ou CSV pelo app Arquivos para restaurar ou mover conteúdo rapidamente.', 'Filtre o conteúdo por tipo, grupo ou status para se concentrar no que precisa.', 'Pesquise textos, imagens e adesivos salvos para encontrar conteúdo instantaneamente.', 'Ordene o conteúdo como preferir para manter os itens relevantes sempre acessíveis.', 'Use a Área de transferência do sistema para levar conteúdo copiado ao LiquidBoard quando precisar.', 'Defina conteúdo para expirar automaticamente e mantenha informações temporárias privadas e organizadas.', 'Sincronize seu conteúdo com segurança pelo iCloud para acessá-lo em todos os dispositivos Apple.'],
  },
  fr: {
    featureParagraphs: ['Créez et modifiez plusieurs modèles de contenu prêts à être envoyés depuis le clavier. Ajoutez des modèles d’e-mail, salutations, coordonnées, liens web, contenu type, codes couleur, prompts IA et brouillons.', 'Stockez vos photos préférées, mèmes, codes QR de paiement et maquettes de conception.', 'Créez des autocollants depuis votre album photo ou des photos existantes pour rendre vos favoris exclusifs.'],
    actionTitles: ['Groupes', 'Épingler', 'Copier', 'Dupliquer', 'Exporter des fichiers', 'Importer des fichiers', 'Filtrer', 'Rechercher', 'Trier', 'Presse-papiers système', 'Contenu éphémère', 'Synchronisation iCloud'],
    actionParagraphs: ['Créez des groupes et organisez textes, images et autocollants selon vos usages. Passez fluidement d’un groupe à l’autre dans l’app clavier.', 'Épinglez en haut les textes, images et autocollants importants que vous utilisez souvent pour les envoyer plus vite.', 'Copiez textes, images et autocollants pour les envoyer ou les réutiliser rapidement.', 'Dupliquez textes, images et autocollants pour créer une version modifiable tout en conservant l’original.', 'Exportez vos données textuelles en fichiers JSON ou CSV via l’app Fichiers.', 'Importez des données textuelles JSON ou CSV depuis l’app Fichiers pour restaurer ou déplacer rapidement votre contenu.', 'Filtrez le contenu par type, groupe ou état pour vous concentrer sur l’essentiel.', 'Recherchez les textes, images et autocollants enregistrés pour trouver instantanément du contenu.', 'Triez le contenu à votre façon pour garder les éléments utiles faciles d’accès.', 'Utilisez le presse-papiers système pour ajouter du contenu copié à LiquidBoard quand vous le souhaitez.', 'Faites expirer automatiquement le contenu pour garder les informations temporaires privées et ordonnées.', 'Synchronisez votre contenu en toute sécurité avec iCloud afin qu’il reste disponible sur vos appareils Apple.'],
  },
  de: {
    featureParagraphs: ['Erstellen und bearbeiten Sie mehrere Inhaltsvorlagen, die direkt über die Tastatur versendet werden können. Fügen Sie E-Mail-Vorlagen, Grüße, Kontaktdaten, Website-Links, Beispielinhalte, Farbcodes, KI-Prompts und Entwürfe hinzu.', 'Speichern Sie Lieblingsfotos, Memes, Zahlungs-QR-Codes und Design-Mockups.', 'Erstellen Sie Sticker aus Ihrem Fotoalbum oder vorhandenen Kamerafotos und machen Sie Ihre Favoriten zu exklusiven Stickern.'],
    actionTitles: ['Gruppen', 'Anheften', 'Kopieren', 'Duplizieren', 'Dateien exportieren', 'Dateien importieren', 'Filtern', 'Suchen', 'Sortieren', 'Systemzwischenablage', 'Ablaufende Inhalte', 'iCloud-Synchronisierung'],
    actionParagraphs: ['Erstellen Sie Gruppen und organisieren Sie Texte, Bilder und Sticker nach Ihrem Bedarf. Wechseln Sie in der Tastatur-App reibungslos zwischen Gruppen.', 'Heften Sie wichtige, häufig verwendete Texte, Bilder und Sticker oben an, um sie schneller zu senden.', 'Kopieren Sie Texte, Bilder und Sticker, um sie schnell zu senden oder wiederzuverwenden.', 'Duplizieren Sie Texte, Bilder und Sticker für eine bearbeitbare Version, während das Original erhalten bleibt.', 'Exportieren Sie Ihre Textdaten über die Dateien-App als JSON- oder CSV-Dateien.', 'Importieren Sie JSON- oder CSV-Textdaten aus der Dateien-App, um Inhalte schnell wiederherzustellen oder zu verschieben.', 'Filtern Sie Inhalte nach Typ, Gruppe oder Status und konzentrieren Sie sich auf das Wesentliche.', 'Durchsuchen Sie gespeicherte Texte, Bilder und Sticker, um Inhalte sofort zu finden.', 'Sortieren Sie Inhalte nach Ihren Vorlieben, damit relevante Elemente immer leicht erreichbar sind.', 'Nutzen Sie die Systemzwischenablage, um kopierte Inhalte bei Bedarf in LiquidBoard zu übernehmen.', 'Lassen Sie Inhalte automatisch ablaufen, damit temporäre Informationen privat und übersichtlich bleiben.', 'Synchronisieren Sie Ihre Inhalte sicher mit iCloud, damit sie auf allen Apple-Geräten verfügbar sind.'],
  },
  ru: {
    featureParagraphs: ['Создавайте и редактируйте шаблоны контента, готовые к отправке с клавиатуры. Добавляйте шаблоны писем, приветствия, контактные данные, ссылки, примеры текста, коды цветов, ИИ-промпты и черновики.', 'Храните любимые фото, мемы, QR-коды для оплаты и дизайн-макеты.', 'Создавайте стикеры из фотоальбома или имеющихся снимков камеры, превращая любимые стикеры в уникальные.'],
    actionTitles: ['Группы', 'Закрепить', 'Копировать', 'Дублировать', 'Экспорт файлов', 'Импорт файлов', 'Фильтровать', 'Поиск', 'Сортировать', 'Системный буфер обмена', 'Исчезающий контент', 'Синхронизация iCloud'],
    actionParagraphs: ['Создавайте группы и организуйте тексты, изображения и стикеры по своим задачам. Плавно переключайтесь между группами в клавиатурном приложении.', 'Закрепляйте сверху важные и часто используемые тексты, изображения и стикеры, чтобы отправлять их быстрее.', 'Копируйте тексты, изображения и стикеры для быстрой отправки или повторного использования.', 'Дублируйте тексты, изображения и стикеры, чтобы создать редактируемую версию и сохранить оригинал.', 'Экспортируйте текстовые данные в файлы JSON или CSV через приложение Файлы.', 'Импортируйте текстовые данные JSON или CSV из приложения Файлы, чтобы быстро восстановить или перенести контент.', 'Фильтруйте контент по типу, группе или статусу, чтобы сосредоточиться на нужном.', 'Ищите среди сохранённых текстов, изображений и стикеров, чтобы сразу находить контент.', 'Сортируйте контент удобным способом, чтобы нужные элементы всегда были под рукой.', 'Используйте системный буфер обмена, чтобы добавлять скопированный контент в LiquidBoard при необходимости.', 'Настройте автоматическое удаление контента, чтобы временная информация оставалась приватной и упорядоченной.', 'Безопасно синхронизируйте контент с iCloud, чтобы он был доступен на всех устройствах Apple.'],
  },
  ko: {
    featureParagraphs: ['키보드에서 바로 보낼 수 있도록 여러 콘텐츠 템플릿을 만들고 편집하세요. 이메일 템플릿, 인사말, 연락처, 웹사이트 링크, 예시 콘텐츠, 색상 코드, AI 프롬프트, 초안을 추가할 수 있습니다.', '좋아하는 사진, 밈, 결제 QR 코드, 디자인 목업을 저장하세요.', '사진 앨범이나 기존 카메라 사진으로 스티커를 만들어 좋아하는 스티커를 나만의 것으로 만드세요.'],
    actionTitles: ['그룹', '고정', '복사', '복제', '파일 내보내기', '파일 가져오기', '필터', '검색', '정렬', '시스템 클립보드', '자동 삭제 콘텐츠', 'iCloud 동기화'],
    actionParagraphs: ['그룹을 만들고 사용 목적에 맞게 텍스트, 이미지, 스티커를 정리하세요. 키보드 앱에서 그룹 간을 부드럽게 전환할 수 있습니다.', '자주 쓰는 중요한 텍스트, 이미지, 스티커를 상단에 고정해 더 빠르게 보낼 수 있습니다.', '텍스트, 이미지, 스티커를 복사해 빠르게 보내거나 다시 사용할 수 있습니다.', '원본은 보존하면서 편집 가능한 버전을 만들 수 있도록 텍스트, 이미지, 스티커를 복제하세요.', '파일 앱을 통해 텍스트 데이터를 JSON 또는 CSV 파일로 내보내세요.', '파일 앱에서 JSON 또는 CSV 텍스트 데이터를 가져와 콘텐츠를 빠르게 복원하거나 이동하세요.', '유형, 그룹 또는 상태별로 콘텐츠를 필터링해 필요한 항목에 집중하세요.', '저장한 텍스트, 이미지, 스티커를 검색해 콘텐츠를 즉시 찾으세요.', '원하는 방식으로 콘텐츠를 정렬해 관련 항목에 언제나 쉽게 접근하세요.', '필요할 때 시스템 클립보드를 사용해 복사한 콘텐츠를 LiquidBoard로 가져오세요.', '콘텐츠가 자동으로 만료되도록 설정해 임시 정보를 비공개로 깔끔하게 유지하세요.', 'iCloud와 안전하게 동기화하여 모든 Apple 기기에서 콘텐츠를 이용하세요.'],
  },
  hi: {
    featureParagraphs: ['कीबोर्ड से भेजने के लिए कई सामग्री टेम्पलेट बनाएँ और संपादित करें। ईमेल टेम्पलेट, अभिवादन, संपर्क जानकारी, वेबसाइट लिंक, नमूना सामग्री, रंग कोड, AI प्रॉम्प्ट और ड्राफ़्ट जोड़ें।', 'अपनी पसंदीदा फ़ोटो, मीम, भुगतान QR कोड और डिज़ाइन मॉकअप सहेजें।', 'फ़ोटो एल्बम या कैमरे की मौजूदा फ़ोटो से स्टिकर बनाएँ और अपने पसंदीदा स्टिकर को विशेष बनाएँ।'],
    actionTitles: ['समूह', 'पिन करें', 'कॉपी करें', 'डुप्लिकेट करें', 'फ़ाइलें एक्सपोर्ट करें', 'फ़ाइलें इंपोर्ट करें', 'फ़िल्टर', 'खोजें', 'क्रमबद्ध करें', 'सिस्टम क्लिपबोर्ड', 'स्वतः मिटने वाला कंटेंट', 'iCloud सिंक'],
    actionParagraphs: ['समूह बनाएँ और उपयोग के अनुसार टेक्स्ट, इमेज और स्टिकर व्यवस्थित करें। कीबोर्ड ऐप में समूहों के बीच आसानी से बदलें।', 'अक्सर उपयोग किए जाने वाले महत्वपूर्ण टेक्स्ट, इमेज और स्टिकर को ऊपर पिन करें ताकि उन्हें तेज़ी से भेज सकें।', 'टेक्स्ट, इमेज और स्टिकर कॉपी करके जल्दी भेजें या फिर से उपयोग करें।', 'मूल को सुरक्षित रखते हुए संपादन योग्य संस्करण बनाने के लिए टेक्स्ट, इमेज और स्टिकर डुप्लिकेट करें।', 'Files ऐप से अपने टेक्स्ट डेटा को JSON या CSV फ़ाइलों के रूप में एक्सपोर्ट करें।', 'कंटेंट को तुरंत पुनर्स्थापित या स्थानांतरित करने के लिए Files ऐप से JSON या CSV टेक्स्ट डेटा इंपोर्ट करें।', 'ज़रूरी चीज़ों पर ध्यान देने के लिए सामग्री को प्रकार, समूह या स्थिति के अनुसार फ़िल्टर करें।', 'सहेजे गए टेक्स्ट, इमेज और स्टिकर खोजकर तुरंत सामग्री पाएँ।', 'सामग्री को अपनी पसंद से क्रमबद्ध करें ताकि प्रासंगिक आइटम हमेशा आसानी से मिलें।', 'ज़रूरत पड़ने पर कॉपी की गई सामग्री को LiquidBoard में लाने के लिए सिस्टम क्लिपबोर्ड का उपयोग करें।', 'अस्थायी जानकारी को निजी और व्यवस्थित रखने के लिए सामग्री को स्वचालित रूप से समाप्त होने दें।', 'iCloud से सुरक्षित सिंक करें ताकि आपकी सामग्री सभी Apple डिवाइस पर उपलब्ध रहे।'],
  },
  bn: {
    featureParagraphs: ['কীবোর্ড থেকে পাঠানোর জন্য একাধিক কনটেন্ট টেমপ্লেট তৈরি ও সম্পাদনা করুন। ইমেইল টেমপ্লেট, অভিবাদন, যোগাযোগের তথ্য, ওয়েবসাইট লিংক, নমুনা কনটেন্ট, রঙের কোড, AI প্রম্পট ও খসড়া যোগ করুন।', 'প্রিয় ছবি, মিম, পেমেন্ট QR কোড এবং ডিজাইন মকআপ সংরক্ষণ করুন।', 'ফটো অ্যালবাম বা ক্যামেরার বিদ্যমান ছবি থেকে স্টিকার তৈরি করে পছন্দের স্টিকারকে একান্ত নিজের করে নিন।'],
    actionTitles: ['গ্রুপ', 'পিন', 'কপি', 'ডুপ্লিকেট', 'ফাইল এক্সপোর্ট', 'ফাইল আমদানি', 'ফিল্টার', 'খোঁজ', 'সাজানো', 'সিস্টেম ক্লিপবোর্ড', 'স্বয়ংক্রিয়ভাবে মুছে যাওয়া কনটেন্ট', 'iCloud সিঙ্ক'],
    actionParagraphs: ['গ্রুপ তৈরি করুন এবং ব্যবহার অনুযায়ী টেক্সট, ছবি ও স্টিকার সাজান। কীবোর্ড অ্যাপে গ্রুপগুলোর মধ্যে সহজে পরিবর্তন করুন।', 'প্রায়শই ব্যবহৃত গুরুত্বপূর্ণ টেক্সট, ছবি ও স্টিকার উপরে পিন করুন যাতে দ্রুত পাঠাতে পারেন।', 'টেক্সট, ছবি ও স্টিকার কপি করে দ্রুত পাঠান বা পুনঃব্যবহার করুন।', 'মূল কনটেন্ট অক্ষত রেখে সম্পাদনাযোগ্য সংস্করণ তৈরির জন্য টেক্সট, ছবি ও স্টিকার ডুপ্লিকেট করুন।', 'Files অ্যাপ দিয়ে টেক্সট ডেটা JSON বা CSV ফাইল হিসেবে এক্সপোর্ট করুন।', 'কনটেন্ট দ্রুত পুনরুদ্ধার বা স্থানান্তরের জন্য Files অ্যাপ থেকে JSON বা CSV টেক্সট ডেটা আমদানি করুন।', 'প্রয়োজনীয় বিষয়ে মনোযোগ দিতে ধরন, গ্রুপ বা অবস্থা অনুযায়ী কনটেন্ট ফিল্টার করুন।', 'সংরক্ষিত টেক্সট, ছবি ও স্টিকার খুঁজে সঙ্গে সঙ্গে কনটেন্ট পান।', 'আপনার পছন্দমতো কনটেন্ট সাজান যাতে প্রাসঙ্গিক আইটেম সবসময় সহজে পাওয়া যায়।', 'প্রয়োজন হলে কপি করা কনটেন্ট LiquidBoard-এ আনতে সিস্টেম ক্লিপবোর্ড ব্যবহার করুন।', 'অস্থায়ী তথ্য ব্যক্তিগত ও গোছানো রাখতে কনটেন্ট স্বয়ংক্রিয়ভাবে মুছে যাওয়ার ব্যবস্থা করুন।', 'সব Apple ডিভাইসে কনটেন্ট উপলভ্য রাখতে iCloud-এর সঙ্গে নিরাপদে সিঙ্ক করুন।'],
  },
  id: {
    featureParagraphs: ['Buat dan edit berbagai templat konten agar siap dikirim dari keyboard. Tambahkan templat email, salam, informasi kontak, tautan situs web, konten contoh, kode warna, prompt AI, dan draf tulisan.', 'Simpan foto favorit, meme, kode QR pembayaran, dan mockup desain.', 'Buat stiker dari album foto atau foto kamera yang tersedia untuk menjadikan stiker favorit Anda eksklusif.'],
    actionTitles: ['Grup', 'Sematkan', 'Salin', 'Duplikat', 'Ekspor file', 'Impor file', 'Filter', 'Cari', 'Urutkan', 'Papan klip sistem', 'Konten kedaluwarsa', 'Sinkronisasi iCloud'],
    actionParagraphs: ['Buat grup dan atur teks, gambar, serta stiker sesuai penggunaan. Beralihlah dengan mulus antargrup di aplikasi keyboard.', 'Sematkan teks, gambar, dan stiker penting yang sering digunakan di atas agar lebih cepat dikirim.', 'Salin teks, gambar, dan stiker untuk dikirim atau digunakan kembali dengan cepat.', 'Duplikat teks, gambar, dan stiker untuk membuat versi yang dapat diedit sambil mempertahankan aslinya.', 'Ekspor data teks sebagai file JSON atau CSV melalui app File.', 'Impor data teks JSON atau CSV dari app File untuk memulihkan atau memindahkan konten dengan cepat.', 'Filter konten berdasarkan jenis, grup, atau status agar fokus pada yang Anda perlukan.', 'Cari teks, gambar, dan stiker tersimpan untuk menemukan konten secara instan.', 'Urutkan konten sesuai keinginan agar item paling relevan selalu mudah dijangkau.', 'Gunakan papan klip sistem untuk membawa konten yang disalin ke LiquidBoard saat diperlukan.', 'Atur konten agar kedaluwarsa otomatis supaya informasi sementara tetap privat dan rapi.', 'Sinkronkan konten dengan aman melalui iCloud agar tersedia di semua perangkat Apple Anda.'],
  },
  it: {
    featureParagraphs: ['Crea e modifica più modelli di contenuto pronti da inviare dalla tastiera. Aggiungi modelli email, saluti, contatti, link web, contenuti di esempio, codici colore, prompt AI e bozze.', 'Conserva foto preferite, meme, codici QR di pagamento e mockup di design.', 'Crea sticker dall’album fotografico o da foto della fotocamera già disponibili per rendere esclusivi i tuoi preferiti.'],
    actionTitles: ['Gruppi', 'Fissa', 'Copia', 'Duplica', 'Esporta file', 'Importa file', 'Filtra', 'Cerca', 'Ordina', 'Appunti di sistema', 'Contenuti a scadenza', 'Sincronizzazione iCloud'],
    actionParagraphs: ['Crea gruppi e organizza testi, immagini e sticker in base all’uso. Passa senza problemi tra i gruppi nell’app tastiera.', 'Fissa in alto testi, immagini e sticker importanti che usi spesso per inviarli più rapidamente.', 'Copia testi, immagini e sticker per inviarli o riutilizzarli rapidamente.', 'Duplica testi, immagini e sticker per creare una versione modificabile mantenendo l’originale.', 'Esporta i dati di testo come file JSON o CSV tramite l’app File.', 'Importa dati di testo JSON o CSV dall’app File per ripristinare o spostare rapidamente i contenuti.', 'Filtra i contenuti per tipo, gruppo o stato per concentrarti su ciò che ti serve.', 'Cerca testi, immagini e sticker salvati per trovare subito i contenuti.', 'Ordina i contenuti come preferisci per avere sempre gli elementi rilevanti a portata di mano.', 'Usa gli appunti di sistema per portare contenuti copiati in LiquidBoard quando ti servono.', 'Imposta la scadenza automatica dei contenuti per mantenere private e ordinate le informazioni temporanee.', 'Sincronizza i contenuti in sicurezza con iCloud per averli disponibili su tutti i tuoi dispositivi Apple.'],
  },
  th: {
    featureParagraphs: ['สร้างและแก้ไขเทมเพลตเนื้อหาหลายรายการให้พร้อมส่งจากคีย์บอร์ด เพิ่มเทมเพลตอีเมล คำทักทาย ข้อมูลติดต่อ ลิงก์เว็บไซต์ เนื้อหาตัวอย่าง รหัสสี AI prompt และฉบับร่างได้', 'จัดเก็บรูปโปรด มีม รหัส QR ชำระเงิน และม็อกอัปการออกแบบ', 'สร้างสติกเกอร์จากอัลบั้มรูปหรือรูปจากกล้องที่มีอยู่ เพื่อเปลี่ยนสติกเกอร์โปรดให้เป็นของคุณโดยเฉพาะ'],
    actionTitles: ['กลุ่ม', 'ปักหมุด', 'คัดลอก', 'ทำสำเนา', 'ส่งออกไฟล์', 'นำเข้าไฟล์', 'ตัวกรอง', 'ค้นหา', 'จัดเรียง', 'คลิปบอร์ดระบบ', 'เนื้อหาลบอัตโนมัติ', 'ซิงค์ iCloud'],
    actionParagraphs: ['สร้างกลุ่มและจัดระเบียบข้อความ รูปภาพ และสติกเกอร์ตามการใช้งาน สลับระหว่างกลุ่มในแอปคีย์บอร์ดได้อย่างลื่นไหล', 'ปักหมุดข้อความ รูปภาพ และสติกเกอร์สำคัญที่ใช้บ่อยไว้ด้านบนเพื่อส่งได้เร็วขึ้น', 'คัดลอกข้อความ รูปภาพ และสติกเกอร์เพื่อส่งหรือนำกลับมาใช้ได้อย่างรวดเร็ว', 'ทำสำเนาข้อความ รูปภาพ และสติกเกอร์เพื่อสร้างเวอร์ชันที่แก้ไขได้โดยเก็บต้นฉบับไว้', 'ส่งออกข้อมูลข้อความเป็นไฟล์ JSON หรือ CSV ผ่านแอปไฟล์', 'นำเข้าข้อมูลข้อความ JSON หรือ CSV จากแอปไฟล์เพื่อกู้คืนหรือย้ายเนื้อหาอย่างรวดเร็ว', 'กรองเนื้อหาตามประเภท กลุ่ม หรือสถานะเพื่อโฟกัสสิ่งที่ต้องการ', 'ค้นหาข้อความ รูปภาพ และสติกเกอร์ที่บันทึกไว้เพื่อพบเนื้อหาทันที', 'จัดเรียงเนื้อหาตามที่ต้องการเพื่อให้รายการสำคัญเข้าถึงได้ง่ายเสมอ', 'ใช้คลิปบอร์ดระบบเพื่อนำเนื้อหาที่คัดลอกมาเข้า LiquidBoard เมื่อจำเป็น', 'ตั้งค่าให้เนื้อหาลบอัตโนมัติเพื่อเก็บข้อมูลชั่วคราวให้เป็นส่วนตัวและเป็นระเบียบ', 'ซิงค์เนื้อหาอย่างปลอดภัยกับ iCloud เพื่อให้พร้อมใช้งานบนอุปกรณ์ Apple ทุกเครื่อง'],
  },
  tl: {
    featureParagraphs: ['Gumawa at mag-edit ng maraming template ng nilalaman na handang ipadala mula sa keyboard. Magdagdag ng mga email template, pagbati, contact information, website link, sample na nilalaman, color code, AI prompt, at draft.', 'Itago ang paboritong larawan, meme, QR code para sa bayad, at design mockup.', 'Gumawa ng sticker mula sa photo album o mga larawang kuha ng camera upang maging eksklusibo ang iyong mga paborito.'],
    actionTitles: ['Mga grupo', 'I-pin', 'Kopyahin', 'I-duplicate', 'Mag-export ng file', 'Mag-import ng file', 'I-filter', 'Maghanap', 'Ayusin', 'System pasteboard', 'Kusang nawawalang content', 'iCloud sync'],
    actionParagraphs: ['Gumawa ng mga grupo at ayusin ang mga text, larawan, at sticker ayon sa gamit. Lumipat nang maayos sa pagitan ng mga grupo sa keyboard app.', 'I-pin sa itaas ang mahahalagang text, larawan, at sticker na madalas mong gamitin upang mas mabilis maipadala.', 'Kopyahin ang mga text, larawan, at sticker upang mabilis na maipadala o magamit muli.', 'I-duplicate ang mga text, larawan, at sticker upang gumawa ng nae-edit na bersyon habang nananatili ang orihinal.', 'I-export ang text data bilang JSON o CSV file sa pamamagitan ng Files app.', 'Mag-import ng JSON o CSV text data mula sa Files app upang mabilis na maibalik o mailipat ang nilalaman.', 'I-filter ang nilalaman ayon sa uri, grupo, o status upang tumuon sa kailangan mo.', 'Maghanap sa mga naka-save na text, larawan, at sticker upang agad makita ang nilalaman.', 'Ayusin ang nilalaman sa gusto mong paraan para laging madaling maabot ang mahahalagang item.', 'Gamitin ang system pasteboard upang dalhin ang nakopyang nilalaman sa LiquidBoard kapag kailangan.', 'Itakda ang content na kusang mawala upang manatiling pribado at maayos ang pansamantalang impormasyon.', 'I-sync nang ligtas sa iCloud upang maging available ang nilalaman sa lahat ng Apple device mo.'],
  },
  pl: {
    featureParagraphs: ['Twórz i edytuj wiele szablonów treści gotowych do wysłania z klawiatury. Dodawaj szablony e-maili, powitania, dane kontaktowe, linki do stron, przykładowe treści, kody kolorów, prompty AI i szkice.', 'Przechowuj ulubione zdjęcia, memy, kody QR do płatności i makiety projektów.', 'Twórz naklejki z albumu zdjęć lub istniejących zdjęć z aparatu, aby ulubione naklejki były wyjątkowo Twoje.'],
    actionTitles: ['Grupy', 'Przypnij', 'Kopiuj', 'Duplikuj', 'Eksport plików', 'Import plików', 'Filtruj', 'Wyszukiwanie', 'Sortowanie', 'Schowek systemowy', 'Treści wygasające', 'Synchronizacja iCloud'],
    actionParagraphs: ['Twórz grupy i organizuj teksty, obrazy oraz naklejki według sposobu użycia. Płynnie przełączaj grupy w aplikacji klawiatury.', 'Przypinaj u góry ważne, często używane teksty, obrazy i naklejki, aby wysyłać je szybciej.', 'Kopiuj teksty, obrazy i naklejki, aby szybko je wysłać lub wykorzystać ponownie.', 'Duplikuj teksty, obrazy i naklejki, aby utworzyć wersję do edycji i zachować oryginał.', 'Eksportuj dane tekstowe jako pliki JSON lub CSV przez aplikację Pliki.', 'Importuj dane tekstowe JSON lub CSV z aplikacji Pliki, aby szybko przywrócić lub przenieść zawartość.', 'Filtruj zawartość według typu, grupy lub stanu, aby skupić się na tym, czego potrzebujesz.', 'Przeszukuj zapisane teksty, obrazy i naklejki, aby natychmiast znaleźć zawartość.', 'Sortuj zawartość po swojemu, aby ważne elementy były zawsze łatwo dostępne.', 'Używaj schowka systemowego, aby w razie potrzeby przenieść skopiowaną zawartość do LiquidBoard.', 'Ustaw automatyczne wygasanie zawartości, aby tymczasowe informacje pozostały prywatne i uporządkowane.', 'Bezpiecznie synchronizuj zawartość z iCloud, aby była dostępna na wszystkich urządzeniach Apple.'],
  },
};

export const getFeatureDetails = (lang: string): FeatureDetails => localized[lang] ?? en;
